r-abishek/rpp

src/include/cpu/rpp_cpu_common.hpp, src/include/cpu/rpp_cpu_simd.hpp, src/modules/cpu/host_tensor_augmentations.hpp, src/modules/rppt_tensor_augmentations.cpp, utilities/rpp-unittests/HOST_NEW/Tensor_host_pkd3.cpp, utilities/rpp-unittests/HOST_NEW/Tensor_host_pln1.cpp, utilities/rpp-unittests/HOST_NEW/Tensor_host_pln3.cpp
- Modify the code to match the new standard and minor changes
=> Resize Bilinear : Tensor Code clean up

src/include/cpu/rpp_cpu_common.hpp, src/include/cpu/rpp_cpu_simd.hpp, src/modules/cpu/host_tensor_augmentations.hpp
*Added for U8 , F32 , I8 , F16 variants
*added for PKD3,PLN3,PLN1 with toggle
=> AVX optimizations for Brightness kernel - HOST

src/include/cpu/rpp_cpu_simd.hpp, src/modules/cpu/kernel/brightness.hpp
*Resolved merge conflicts and updated brigntness.hpp with latest SSE and AVX2 codes
=> [Updated] AVX optimizations for Brightness kernel - HOST

src/include/cpu/rpp_cpu_simd.hpp
*moved masks variables defined inside load functions to outside and defined as global constants
*renamed mask variables
=> Updated Masks used for load and store in Tensor support - HOST

src/modules/cpu/kernel/flip.hpp, src/modules/hip/kernel/flip.hpp
*updated the branching structure in flip HIP 
*updated the condition for no flip case in flip HOST
=> [PR comments changes] Flip Tensor implementation on HOST and HIP

include/rppt_tensor_geometric_augmentations.h, src/modules/cpu/host_tensor_geometric_augmentations.hpp, src/modules/cpu/kernel/resize_crop_mirror.hpp, src/modules/hip/hip_tensor_geometric_augmentations.hpp, src/modules/hip/kernel/resize_crop_mirror.hpp, src/modules/rppt_tensor_geometric_augmentations.cpp, utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pkd3.cpp, utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pln1.cpp, utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pln3.cpp, utilities/rpp-performancetests/HOST_NEW/Tensor_host_pkd3.cpp, utilities/rpp-performancetests/HOST_NEW/Tensor_host_pln1.cpp, utilities/rpp-performancetests/HOST_NEW/Tensor_host_pln3.cpp, utilities/rpp-unittests/HIP_NEW/Tensor_hip_pkd3.cpp, utilities/rpp-unittests/HIP_NEW/Tensor_hip_pln1.cpp, utilities/rpp-unittests/HIP_NEW/Tensor_hip_pln3.cpp, utilities/rpp-unittests/HOST_NEW/Tensor_host_pkd3.cpp, utilities/rpp-unittests/HOST_NEW/Tensor_host_pln1.cpp, utilities/rpp-unittests/HOST_NEW/Tensor_host_pln3.cpp
*Added for U8 , F32 , I8 , F16 variants
*added for PKD3,PLN3,PLN1 with toggle
=> Resize Crop Mirror - HOST Tensor AVX2 Support and Vectorized HIP support

src/modules/cpu/kernel/crop_mirror_normalize.hpp, src/modules/hip/kernel/crop_mirror_normalize.hpp, utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pln1.cpp, utilities/rpp-unittests/HIP_NEW/Tensor_hip_pkd3.cpp, utilities/rpp-unittests/HIP_NEW/Tensor_hip_pln1.cpp
- Removed saturation for U8-F32, U8-F16 variant
- Added fix to handle the mirror case for CMN HIP
=> Crop Mirror Normalize changes

src/modules/rppt_tensor_geometric_augmentations.cpp, utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pkd3.cpp, utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pln1.cpp, utilities/rpp-performancetests/HIP_NEW/Tensor_hip_pln3.cpp, utilities/rpp-unittests/HIP_NEW/Tensor_hip_pkd3.cpp, utilities/rpp-unittests/HIP_NEW/Tensor_hip_pln1.cpp, utilities/rpp-unittests/HIP_NEW/Tensor_hip_pln3.cpp
- Fix rotate algorithm
- Fix build issue in HIP test suite
=> Rotate Fix

Readme.md, utilities/test_suite/HIP/Tensor_hip.cpp, utilities/test_suite/HIP/runTests.py, utilities/test_suite/HIP/testAllScript.sh, utilities/test_suite/HOST/Tensor_host.cpp, utilities/test_suite/HOST/runTests.py, utilities/test_suite/HOST/testAllScript.sh, utilities/test_suite/README.md
* added changes to resolve codacy warnings
* updated instructions for installing turbojpeg
=> Codacy fixes for Test suite

utilities/test_suite/HIP/Tensor_hip.cpp, utilities/test_suite/HIP/runTests.py, utilities/test_suite/HOST/Tensor_host.cpp, utilities/test_suite/HOST/runTests.py, utilities/test_suite/README.md, utilities/test_suite/rpp_test_suite_common.h
- Added fixes for new codacy warnings
- numIterations as a parameter from python
- To report user on the number of valid cases being run in QA mode
- Units reported as ms / batch
=> Codacy Fixes

utilities/test_suite/HIP/Tensor_hip.cpp, utilities/test_suite/HOST/Tensor_host.cpp
Confirmed outputs in 2 machines with new fix.
=> Fix HOST testsuite

src/modules/hip/kernel/gaussian_filter.hpp, src/modules/rppt_tensor_filter_augmentations.cpp, utilities/test_suite/HIP/runTests.py, utilities/test_suite/HIP/testAllScript.sh, utilities/test_suite/HOST/runTests.py, utilities/test_suite/HOST/testAllScript.sh
=> Gaussian filter HIP - Codacy fixes

src/modules/cpu/kernel/water.hpp, src/modules/hip/kernel/water.hpp
- Changed casting to c++ style in internal water kernel codes
- Removed unsed variables
=> Water Tensor - Codacy fixes

utilities/rpp-performancetests/HIP_NEW/uniqueFunctionalities_hip.cpp, utilities/rpp-performancetests/HOST_NEW/uniqueFunctionalities_host.cpp, utilities/rpp-unittests/HIP_NEW/uniqueFunctionalities_hip.cpp, utilities/rpp-unittests/HOST_NEW/uniqueFunctionalities_host.cpp
- added maps for supported functionalities in HOST and HIP test suites
- added for both unit and performance tests
=> Changes in unique functionalities test suite

src/modules/cpu/kernel/tensor_sum.hpp
Confirmed performance and QA tests
=> Cleanup and minor optimization

include/rppt_tensor_arithmetic_operations.h, include/rppt_tensor_geometric_augmentations.h, src/modules/cpu/kernel/slice.hpp, src/modules/hip/kernel/fmadd_scalar.hpp, src/modules/hip/kernel/slice.hpp, src/modules/rppt_tensor_arithmetic_operations.cpp, src/modules/rppt_tensor_geometric_augmentations.cpp, utilities/test_suite/HIP/Tensor_voxel_hip.cpp, utilities/test_suite/HIP/runTests_voxel.py, utilities/test_suite/HOST/Tensor_voxel_host.cpp, utilities/test_suite/HOST/runTests_voxel.py, utilities/test_suite/rpp_test_suite_voxel.h
Also includes U8 support for slice
=> Fix issues in Voxel kernels

utilities/test_suite/HIP/Tensor_voxel_hip.cpp, utilities/test_suite/HIP/runTests_voxel.py, utilities/test_suite/HOST/Tensor_voxel_host.cpp, utilities/test_suite/HOST/runTests_voxel.py
- added seperate functions for running unit tests and performance tests
- removed redundant condition checks
=> Voxel Test suite changes

utilities/test_suite/HOST/runAudioTests.py
- Added separate variables for min and max case numbers supported in test suite
=> Audio python test suite changes

src/modules/cpu/kernel/tensor_max.hpp, src/modules/cpu/kernel/tensor_min.hpp
=> Resolve codacy warnings in Tensor min/max Kernel

src/include/cpu/rpp_cpu_common.hpp, src/include/cpu/rpp_cpu_simd.hpp, src/modules/cpu/kernel/tensor_max.hpp, src/modules/cpu/kernel/tensor_min.hpp
Added further cleanup as per Rajy's comments
=> Tensor min/max HOST

include/rppt_tensor_audio_augmentations.h, src/modules/cpu/kernel/down_mixing.hpp, src/modules/rppt_tensor_audio_augmentations.cpp, utilities/test_suite/HOST/Tensor_host_audio.cpp
- combined srcLength and channels into single tensor
- Made corresponding changes in test suite
=> Downmixing - changes as per review comments

src/modules/hip/kernel/noise_gaussian.hpp, utilities/test_suite/HIP/Tensor_voxel_hip.cpp
- Added the input, output adjustment required for HIP kernel
- Fixed the bug in handle creation in voxel hip test suite
=> Bug fixes for gaussian noise voxel HIP

src/modules/cpu/kernel/spectrogram.hpp
Address review comments and few more optimizations
=> Spectrogram address latest review comments

include/rppdefs.h, include/rppt_tensor_audio_augmentations.h, src/modules/cpu/kernel/pre_emphasis_filter.hpp, src/modules/cpu/kernel/spectrogram.hpp, src/modules/rppt_tensor_audio_augmentations.cpp, utilities/test_suite/HOST/Tensor_audio_host.cpp, utilities/test_suite/rpp_test_suite_audio.h
- Adds the correct api for spectrogram and relevant changes in test suite
- Bug fix for preemphasis filter
=> Merge fixes for audio augmentations

utilities/test_suite/HIP/Tensor_hip.cpp, utilities/test_suite/HOST/Tensor_host.cpp
- Adds Noise test case in tensor test suite
=> Noise Test Suite Addition

src/include/cpu/rpp_cpu_simd.hpp, src/modules/cpu/kernel/remap.hpp, src/modules/cpu/kernel/resize.hpp, src/modules/cpu/kernel/warp_affine.hpp
- removed unnecessary inline helper functions
=> Remap PR changes based on review comments

utilities/test_suite/HIP/runMiscTests.py, utilities/test_suite/HIP/runTests.py, utilities/test_suite/HIP/runVoxelTests.py, utilities/test_suite/HOST/runAudioTests.py, utilities/test_suite/HOST/runMiscTests.py, utilities/test_suite/HOST/runTests.py, utilities/test_suite/HOST/runVoxelTests.py, utilities/test_suite/common.py
- Add test suite changes to print augmentation map in help
=> RPP test suite change - Add augmentation map to help

utilities/test_suite/HIP/runTests.py, utilities/test_suite/HOST/runTests.py, utilities/test_suite/common.py
- Add new augmentation group map
- Modified function group finder function
=> RPP Test Suite - Function Group Modification

utilities/test_suite/HIP/runMiscTests.py, utilities/test_suite/HIP/runTests.py, utilities/test_suite/HIP/runVoxelTests.py, utilities/test_suite/HOST/runAudioTests.py, utilities/test_suite/HOST/runMiscTests.py, utilities/test_suite/HOST/runTests.py, utilities/test_suite/HOST/runVoxelTests.py, utilities/test_suite/common.py
- moved the  common code in python scripts to common.py
=> Rpp Test Suite - Resolve review comments

src/modules/cpu/kernel/transpose.hpp
- changed 2d function name to 2d_pln1_compute
- change to &~ for aligned length - multiple instances for powers of 2 only.
- change to k++ instead of k = (i/4)
- added comment for exit case of recursion
=> Transpose changes based on review comments

include/rppdefs.h, src/modules/hip/kernel/non_silent_region_detection.hpp, utilities/test_suite/CMakeLists.txt
- added const variable for maximum MMS buffer size
- added CTests for audio HIP kernels
- added few more comments in moving mean square hip kernel
=> NSR HIP - Address review comments

utilities/test_suite/HIP/runVoxelTests.py, utilities/test_suite/HOST/runTests.py, utilities/test_suite/common.py
=> RPP Test Suite : Fix CI Failures

utilities/test_suite/HIP/runAudioTests.py, utilities/test_suite/HOST/Tensor_audio_host.cpp, utilities/test_suite/common.py, utilities/test_suite/rpp_test_suite_audio.h
- added fixes for python2 compatibility
- added fix for help function
- added fix for audio descriptor dims in audio host test suite
=> NSR HIP -  Audio HIP Test suite changes for python 2 compatibility

include/rppdefs.h, include/rppt_tensor_audio_augmentations.h, src/modules/rppt_tensor_audio_augmentations.cpp, utilities/test_suite/HIP/runAudioTests.py, utilities/test_suite/HOST/Tensor_audio_host.cpp, utilities/test_suite/common.py, utilities/test_suite/rpp_test_suite_audio.h
- added fixes for python2 compatibility
- added fix for help function
- added fix for audio descriptor dims in audio host test suite
=> ToDecibels HIP - Audio HIP Test suite changes for python 2 compatibility

include/rppdefs.h, include/rppt_tensor_audio_augmentations.h, src/modules/rppt_tensor_audio_augmentations.cpp, utilities/test_suite/HIP/Tensor_audio_hip.cpp, utilities/test_suite/HIP/runAudioTests.py, utilities/test_suite/HOST/Tensor_audio_host.cpp, utilities/test_suite/common.py, utilities/test_suite/rpp_test_suite_audio.h
- added fixes for python2 compatibility
- added fix for help function
- added fix for audio descriptor dims in audio host test suite
=> Downmixing HIP - Audio HIP Test suite changes for python 2 compatibility

src/modules/rppt_tensor_audio_augmentations.cpp
- Fixes the warnings in the build
=> Rpp Pre Emphasis Filter - Fix Build warnings

utilities/test_suite/HIP/Tensor_hip.cpp
- Fixes errors in the HIP test suite
=> RPP Pixelate - Fix HIP Test Suite Errors

utilities/test_suite/HIP/Tensor_hip.cpp, utilities/test_suite/HIP/Tensor_voxel_hip.cpp, utilities/test_suite/HIP/runAudioTests.py, utilities/test_suite/HIP/runMiscTests.py, utilities/test_suite/HIP/runTests.py, utilities/test_suite/HIP/runVoxelTests.py, utilities/test_suite/HOST/Tensor_host.cpp, utilities/test_suite/HOST/Tensor_voxel_host.cpp, utilities/test_suite/HOST/runAudioTests.py, utilities/test_suite/HOST/runMiscTests.py, utilities/test_suite/HOST/runTests.py, utilities/test_suite/HOST/runVoxelTests.py, utilities/test_suite/common.py, utilities/test_suite/rpp_test_suite_common.h
- Clean up test suite  code and removes empty lines
=> RPP Test Suite - Remove Empty Lines and Cleanup

utilities/test_suite/README.md
- Updated the turbojpeg installation in readme
=> TurboJpeg Readme update

include/rppt_tensor_audio_augmentations.h, src/include/hip/rpp_hip_common.hpp, src/modules/hip/kernel/resample.hpp, src/modules/rppt_tensor_audio_augmentations.cpp
- added MACRO for doing floor operation on float4 variable
- added numDims validation check for NSR HIP kernel
=> Address review comments for Resample HIP

src/include/cpu/rpp_cpu_common.hpp, src/modules/cpu/kernel/noise_gaussian.hpp
- Fixed the bug in copy function for NCDHW layout
- Fixed the ROI updation for NDHWC layout
=> Bug fix for copy function used in gaussian noise voxel HOST kernel

utilities/test_suite/HIP/Tensor_audio_hip.cpp, utilities/test_suite/HIP/Tensor_hip.cpp, utilities/test_suite/HIP/Tensor_misc_hip.cpp, utilities/test_suite/HIP/Tensor_voxel_hip.cpp, utilities/test_suite/HOST/Tensor_audio_host.cpp, utilities/test_suite/HOST/Tensor_host.cpp, utilities/test_suite/HOST/Tensor_misc_host.cpp, utilities/test_suite/HOST/Tensor_voxel_host.cpp, utilities/test_suite/rpp_test_suite_audio.h, utilities/test_suite/rpp_test_suite_voxel.h
- Replaces all the printfs with cout in test suite files
=> RPP Test suite - Replace Printf statements with cout

include/rppdefs.h, include/rppt_tensor_audio_augmentations.h, src/include/hip/rpp_hip_common.hpp, src/modules/hip/hip_tensor_audio_augmentations.hpp, src/modules/hip/kernel/pre_emphasis_filter.hpp, src/modules/rppt_tensor_audio_augmentations.cpp, utilities/test_suite/HIP/Tensor_audio_hip.cpp, utilities/test_suite/HIP/runAudioTests.py, utilities/test_suite/HOST/Tensor_audio_host.cpp
- merged with latest changes in develop and resolved conflicts
- modified MACRO for FLOOR4 
- modified sinc function to use an approximation for 1.0f/6
=> Resample HIP - Develop merge and changes based on review comments

utilities/test_suite/HOST/runTests.py, utilities/test_suite/common.py, utilities/test_suite/rpp_test_suite_common.h, utilities/test_suite/rpp_test_suite_voxel.h
- Include header for map in test suite and bug fix in the HOST test suite
- update Augmentation Maps and Function grouping Map
=> RPP Test Suite - Bug Fix in HOST test suite and Update Augmentation Maps

docs/sphinx/requirements.in, docs/sphinx/requirements.txt, include/rppt_tensor_effects_augmentations.h, include/rppt_tensor_geometric_augmentations.h, src/modules/rppt_tensor_audio_augmentations.cpp, src/modules/rppt_tensor_effects_augmentations.cpp, utilities/test_suite/HIP/Tensor_audio_hip.cpp, utilities/test_suite/HIP/Tensor_hip.cpp, utilities/test_suite/HIP/Tensor_misc_hip.cpp, utilities/test_suite/HIP/Tensor_voxel_hip.cpp, utilities/test_suite/HIP/runAudioTests.py, utilities/test_suite/HIP/runMiscTests.py, utilities/test_suite/HIP/runTests.py, utilities/test_suite/HIP/runVoxelTests.py, utilities/test_suite/HOST/Tensor_audio_host.cpp, utilities/test_suite/HOST/Tensor_host.cpp, utilities/test_suite/HOST/Tensor_misc_host.cpp, utilities/test_suite/HOST/Tensor_voxel_host.cpp, utilities/test_suite/HOST/runAudioTests.py, utilities/test_suite/HOST/runMiscTests.py, utilities/test_suite/HOST/runTests.py, utilities/test_suite/HOST/runVoxelTests.py, utilities/test_suite/common.py, utilities/test_suite/rpp_test_suite_audio.h, utilities/test_suite/rpp_test_suite_common.h, utilities/test_suite/rpp_test_suite_voxel.h
- Merged with latest changes in develop
- modified audio augmentation map in common.py
- reverted the numDims validation check for audio HOST kernel temporarily
=> Spectrogram HIP TOT Merge

CHANGELOG.md, CMakeLists.txt, README.md, include/rpp_version.h, include/rppdefs.h, src/include/cpu/rpp_cpu_common.hpp, src/modules/hip/kernel/resample.hpp, src/modules/rppt_tensor_audio_augmentations.cpp, utilities/test_suite/HIP/Tensor_audio_hip.cpp, utilities/test_suite/HOST/Tensor_audio_host.cpp, utilities/test_suite/common.py, utilities/test_suite/rpp_test_suite_audio.h, utilities/test_suite/rpp_test_suite_common.h, utilities/test_suite/rpp_test_suite_voxel.h
- Merged with latest develop changes
- Modified version number in required files
=> Box filter HOST TOT Merge

src/modules/hip/handlehip.cpp
- check the return status of HIP apis used for memory allocation and deallocation in handle
=> RPP HIP Handle memory allocations validation

src/modules/hip/handlehip.cpp
=> RPP Spectrogram HIP TOT Merge

utilities/test_suite/rpp_test_suite_common.h, utilities/test_suite/rpp_test_suite_voxel.h
- includes iomanip header in test suite
=> RPP Test Suite : Include Iomanip header

src/modules/cpu/kernel/mel_filter_bank.hpp, src/modules/hip/kernel/mel_filter_bank.hpp, src/modules/rppt_tensor_audio_augmentations.cpp, utilities/test_suite/HIP/runAudioTests.py
- Add algorithm description for mfb and checks for the min and max frequencies
=> RPP Mel Filter Bank - Add Algorithm description and validations check for some parameters

utilities/test_suite/rpp_test_suite_image.h
- fixed the errors in the test suite
=> RPP BOX Filter : Fix CI issues

utilities/test_suite/rpp_test_suite_audio.h
=> RPP Mel Filter Bank - Fix CI issues

include/rppdefs.h, utilities/test_suite/HIP/Tensor_image_hip.cpp, utilities/test_suite/HIP/runAudioTests.py, utilities/test_suite/HIP/runImageTests.py, utilities/test_suite/HIP/runMiscTests.py, utilities/test_suite/HIP/runVoxelTests.py, utilities/test_suite/HOST/Tensor_image_host.cpp, utilities/test_suite/HOST/runAudioTests.py, utilities/test_suite/HOST/runImageTests.py, utilities/test_suite/HOST/runMiscTests.py, utilities/test_suite/HOST/runVoxelTests.py, utilities/test_suite/common.py
- Fix issue of renaming tensor_host and tensor_hip to tensor_image_host and tensor_image_hip
- Improved the error display of not implemented CPP_APIs
=> Test suite - Error code detection and display fix 

utilities/test_suite/HIP/runAudioTests.py, utilities/test_suite/HIP/runImageTests.py, utilities/test_suite/HIP/runMiscTests.py, utilities/test_suite/HIP/runVoxelTests.py, utilities/test_suite/HOST/Tensor_image_host.cpp, utilities/test_suite/HOST/runAudioTests.py, utilities/test_suite/HOST/runImageTests.py, utilities/test_suite/HOST/runMiscTests.py, utilities/test_suite/HOST/runVoxelTests.py, utilities/test_suite/common.py
- Fix for unable to open file for Rain and warp_perspective
- Enhancement for displaying not existing RPP functionality .
=> Test suite - Error code detection and display fix and Enhancement

cmake/FindTurboJpeg.cmake, utilities/test_suite/README.md
- Adds Necessary changes for the turboJpeg package installation
=> RPP Turbo JPEG Package Installation

src/modules/cpu/kernel/gaussian_filter.hpp, utilities/test_suite/HIP/runAudioTests.py, utilities/test_suite/HIP/runImageTests.py, utilities/test_suite/HIP/runMiscTests.py, utilities/test_suite/HIP/runVoxelTests.py, utilities/test_suite/HOST/runAudioTests.py, utilities/test_suite/HOST/runImageTests.py, utilities/test_suite/HOST/runMiscTests.py, utilities/test_suite/HOST/runVoxelTests.py, utilities/test_suite/common.py, utilities/test_suite/rpp_test_suite_image.h
- Fixed the QA summary
- Fixed the issue of not printing the table in performance tests
- Fixed the issue of unit tests not running for Gaussian filter
=> RPP Test suite: Fix Summary and Gaussian unit test issues

docs/sphinx/requirements.in, docs/sphinx/requirements.txt, src/modules/CMakeLists.txt, src/modules/tensor/cpu/kernel/gaussian_filter.cpp, utilities/test_suite/HIP/runAudioTests.py, utilities/test_suite/HIP/runImageTests.py, utilities/test_suite/HIP/runMiscTests.py, utilities/test_suite/HIP/runVoxelTests.py, utilities/test_suite/HOST/runAudioTests.py, utilities/test_suite/HOST/runImageTests.py, utilities/test_suite/HOST/runMiscTests.py, utilities/test_suite/HOST/runVoxelTests.py, utilities/test_suite/common.py, utilities/test_suite/rpp_test_suite_image.h
Latest develop merge and fixes for QA audio HOST Test Suite
=> Hip host build parallelized - After latest merge

src/modules/tensor/cpu/kernel/jpeg_compression_distortion.cpp
- resolve the review comments  from srihari
=> Jpeg compression distortion - resolved review comments

api/rppt_tensor_geometric_augmentations.h, src/modules/tensor/cpu/kernel/jpeg_compression_distortion.cpp, utilities/test_suite/HOST/runImageTests.py
- Resolved the review comments
=> RPP JPEG compression HOST : Resolve review comments

src/include/common/cpu/rpp_cpu_simd_math.hpp, src/modules/tensor/cpu/kernel/jpeg_compression_distortion.cpp
- Resolved the review comments
=> RPP JPEG COMPRESSION DISTORTION : Resolve review comments

src/modules/tensor/cpu/kernel/color_to_greyscale.cpp, src/modules/tensor/cpu/kernel/color_twist.cpp
Fixes to SSE version of color_twist and color_to_greyscale
=> Fixes for SSE version of color_twist and color_to_greyscale

src/include/common/cpu/rpp_cpu_simd_load_store.hpp, src/modules/tensor/cpu/kernel/blend.cpp, src/modules/tensor/cpu/kernel/brightness.cpp, src/modules/tensor/cpu/kernel/crop.cpp, src/modules/tensor/cpu/kernel/crop_and_patch.cpp, src/modules/tensor/cpu/kernel/threshold.cpp
- Resolved review comments added by Rajy
- Modified SIMD print functions to use union which help us eliminating an extra storeu_ps instruction
=> RPP F32 QA : Review Comments Resolution

src/modules/tensor/cpu/kernel/box_filter.cpp, utilities/test_suite/HIP/Tensor_misc_hip.cpp, utilities/test_suite/HOST/Tensor_misc_host.cpp, utilities/test_suite/rpp_test_suite_misc.h
The PR contains bug fixes for log1p test suite and box filter QA Mismatches
=> Log1p  and Box Filter QA Test fixes

src/modules/tensor/cpu/kernel/box_filter.cpp
The PR aims to remove the hardcoding changes inside the branch for box filter
=> Remove hardcoding of channel details

src/modules/tensor/cpu/kernel/box_filter.cpp, src/modules/tensor/cpu/kernel/flip.cpp, src/modules/tensor/cpu/kernel/gaussian_filter.cpp, src/modules/tensor/cpu/kernel/threshold.cpp, src/modules/tensor/cpu/kernel/water.cpp, utilities/test_suite/HIP/Tensor_image_hip.cpp, utilities/test_suite/HIP/runImageTests.py, utilities/test_suite/HOST/Tensor_image_host.cpp, utilities/test_suite/HOST/runImageTests.py, utilities/test_suite/common.py
- Fixed the RPP_ERROR printing in the logs
- Fixed the memory related issues in few kernels
- Fixed the incorrect output images after case 26
@r-abishek  all the issues you mentioned except the threshold u8 and I8 are resolved now
=> Fix the bugs in test suite and Memory related issues in few kernels

utilities/test_suite/rpp_test_suite_audio.h
The PR is to address the copilot suggestions on spectrogram/resample fix PR.
=> Audio fix comments - Copilot

src/include/common/cpu/rpp_cpu_simd_load_store.hpp, src/modules/tensor/cpu/kernel/tensor_max.cpp, src/modules/tensor/cpu/kernel/tensor_mean.cpp, src/modules/tensor/cpu/kernel/tensor_min.cpp, src/modules/tensor/cpu/kernel/tensor_stddev.cpp, src/modules/tensor/cpu/kernel/tensor_sum.cpp
=> Add F16 Load/Store Updates for 5 kernels
